#include <stdio.h>
int main()
{
    printf("Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year
    Happy New Year
   Happy New Year
  Happy New Year
 Happy New Year
Happy New Year
Happy New Year
 Happy New Year
  Happy New Year
   Happy New Year
    Happy New Year
     Happy New Year
      Happy New Year
       Happy New Year
        Happy New Year
         Happy New Year
          Happy New Year
           Happy New Year
            Happy New Year
             Happy New Year
              Happy New Year
               Happy New Year
                Happy New Year
                 Happy New Year
                  Happy New Year
                   Happy New Year
                    Happy New Year
                     Happy New Year
                      Happy New Year
                       Happy New Year
                        Happy New Year
                         Happy New Year
                          Happy New Year
                           Happy New Year
                            Happy New Year
                             Happy New Year
                              Happy New Year
                             Happy New Year
                            Happy New Year
                           Happy New Year
                          Happy New Year
                         Happy New Year
                        Happy New Year
                       Happy New Year
                      Happy New Year
                     Happy New Year
                    Happy New Year
                   Happy New Year
                  Happy New Year
                 Happy New Year
                Happy New Year
               Happy New Year
              Happy New Year
             Happy New Year
            Happy New Year
           Happy New Year
          Happy New Year
         Happy New Year
        Happy New Year
       Happy New Year
      Happy New Year
     Happy New Year");
    return 0;
}
