#Python Program to draw indian 
# Flag
import turtle
from turtle import*
screen = turtle.Screen()
flag = turtle.Turtle()
speed(0)
flag.penup()
flag.goto(-400, 250)
flag.pendown()
flag.color("orange")
flag.begin_fill()
flag.forward(800)
flag.right(90)
flag.forward(167)
flag.right(90)
flag.forward(800)
flag.end_fill()
flag.left(90)
flag.forward(167)
flag.color("green")
flag.begin_fill()
flag.forward(167)
flag.left(90)
flag.forward(800)
flag.left(90)
flag.forward(167)
flag.end_fill()
flag.penup()
flag.goto(70, 0)
flag.pendown()
flag.color("navy")
flag.begin_fill()
flag.circle(70)
flag.end_fill()
flag.penup()
flag.goto(60, 0)
flag.pendown()
flag.color("white")
flag.begin_fill()
flag.circle(60)
flag.end_fill()
flag.penup()
flag.goto(-57, -8)
flag.pendown()
flag.color("navy")
for i in range(24):
    flag.begin_fill()
    flag.circle(3)
    flag.end_fill()
    flag.penup()
    flag.forward(15)
    flag.right(15)
    flag.pendown()
flag.penup()
flag.goto(20, 0)
flag.pendown()
flag.begin_fill()
flag.circle(20)
flag.end_fill()
flag.penup()
flag.goto(0, 0)
flag.pendown()
flag.pensize(2)
for i in range(24):
    flag.forward(60)
    flag.backward(60)
    flag.left(15)
turtle.done()